export const ACTIVITY_LOG_ACTIONS = {
  // Auth
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  
  // Users
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  CHANGE_USER_STATUS: 'CHANGE_USER_STATUS',
  RESET_PASSWORD: 'RESET_PASSWORD',
  
  // Agencies
  CREATE_AGENCY: 'CREATE_AGENCY',
  UPDATE_AGENCY: 'UPDATE_AGENCY',
  DELETE_AGENCY: 'DELETE_AGENCY',
  CHANGE_AGENCY_STATUS: 'CHANGE_AGENCY_STATUS',
  CHANGE_AGENCY_PLAN: 'CHANGE_AGENCY_PLAN',
  
  // Tickets
  CREATE_TICKET: 'CREATE_TICKET',
  UPDATE_TICKET: 'UPDATE_TICKET',
  DELETE_TICKET: 'DELETE_TICKET',
  FINALIZE_TICKET: 'FINALIZE_TICKET',
  REQUEST_UNLOCK_TICKET: 'REQUEST_UNLOCK_TICKET',
  APPROVE_UNLOCK_TICKET: 'APPROVE_UNLOCK_TICKET',
  REJECT_UNLOCK_TICKET: 'REJECT_UNLOCK_TICKET',
  FORCE_UNLOCK_TICKET: 'FORCE_UNLOCK_TICKET',
  
  // Invoices
  CREATE_INVOICE: 'CREATE_INVOICE',
  UPDATE_INVOICE: 'UPDATE_INVOICE',
  DELETE_INVOICE: 'DELETE_INVOICE',
  APPROVE_INVOICE: 'APPROVE_INVOICE',
  PAY_INVOICE: 'PAY_INVOICE',
  
  // Payments
  CREATE_PAYMENT: 'CREATE_PAYMENT',
  DELETE_PAYMENT: 'DELETE_PAYMENT',
  
  // Bank Cards
  CREATE_BANK_CARD: 'CREATE_BANK_CARD',
  UPDATE_BANK_CARD: 'UPDATE_BANK_CARD',
  DELETE_BANK_CARD: 'DELETE_BANK_CARD',
  ACTIVATE_BANK_CARD: 'ACTIVATE_BANK_CARD',
  DEACTIVATE_BANK_CARD: 'DEACTIVATE_BANK_CARD',
  SET_DEFAULT_BANK_CARD: 'SET_DEFAULT_BANK_CARD',
  
  // Organizations
  CREATE_ORGANIZATION: 'CREATE_ORGANIZATION',
  UPDATE_ORGANIZATION: 'UPDATE_ORGANIZATION',
  DELETE_ORGANIZATION: 'DELETE_ORGANIZATION',
  CREATE_ORGANIZATION_ADMIN: 'CREATE_ORGANIZATION_ADMIN',
  
  // Support Tickets
  CREATE_SUPPORT_TICKET: 'CREATE_SUPPORT_TICKET',
  REPLY_TO_SUPPORT_TICKET: 'REPLY_TO_SUPPORT_TICKET',
  FORWARD_SUPPORT_TICKET: 'FORWARD_SUPPORT_TICKET',
  CLOSE_SUPPORT_TICKET: 'CLOSE_SUPPORT_TICKET',
  
  // Plans
  CREATE_PLAN: 'CREATE_PLAN',
  UPDATE_PLAN: 'UPDATE_PLAN',
  DELETE_PLAN: 'DELETE_PLAN',
  AUTO_RENEW_PLAN: 'AUTO_RENEW_PLAN',
  TRIAL_EXPIRED: 'TRIAL_EXPIRED',
  
  // Registration Requests
  CREATE_REGISTRATION_REQUEST: 'CREATE_REGISTRATION_REQUEST',
  UPDATE_REGISTRATION_REQUEST: 'UPDATE_REGISTRATION_REQUEST',
  DELETE_REGISTRATION_REQUEST: 'DELETE_REGISTRATION_REQUEST',
  APPROVE_REGISTRATION_REQUEST: 'APPROVE_REGISTRATION_REQUEST',
  REJECT_REGISTRATION_REQUEST: 'REJECT_REGISTRATION_REQUEST',
  
  // Airports
  CREATE_AIRPORT: 'CREATE_AIRPORT',
  UPDATE_AIRPORT: 'UPDATE_AIRPORT',
  DELETE_AIRPORT: 'DELETE_AIRPORT',
  
  // Airlines
  CREATE_AIRLINE: 'CREATE_AIRLINE',
  UPDATE_AIRLINE: 'UPDATE_AIRLINE',
  DELETE_AIRLINE: 'DELETE_AIRLINE',
} as const;

export type ActivityLogAction = (typeof ACTIVITY_LOG_ACTIONS)[keyof typeof ACTIVITY_LOG_ACTIONS];

export const ACTIVITY_LOG_CACHE_KEYS = {
  STATS: 'activity_logs:stats',
  USER_LOGS: (userId: string) => `activity_logs:user:${userId}`,
  AGENCY_LOGS: (agencyId: string) => `activity_logs:agency:${agencyId}`,
} as const;